### ISSUE TITLE
develop ProgPoW

### ISSUE THREAD

**Issue by hackmod** [ethersocial/proposals#10]
ProgPoW has been suggested as [EIP-1057](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1057.md) and currently under development but almost ready.
The latest ProgPoW spec ~~v0.9.1~~ v0.9.2 has been implemented as several other languages

several ethereum projects or ethash libraries like as go-ethereum / parity / ethash are under development to support latest ProgPoW spec.
go-ethereum / parity / ethash 등등은 다음과 같이 ProgPoW 지원을 위한 준비가 한창 진행중입니다.

ProgPoW spec - ~~11/17~~ ~~12/03 latest spec v0.9.1~~ 12/08 spec v0.9.2
- https://github.com/ifdefelse/ProgPOW (cpp, ethminer based ProgPoW algorithm, ProgPoW spec v0.9.1)
- https://github.com/ethereum/go-ethereum (golang, latest v0.9.1 spec support)
- https://github.com/chfast/ethash - (cpp, latest v0.9.1 spec)
- https://github.com/paritytech/parity-ethereum PR at 9762 (rust v0.8 ProgPoW spec)

some ethereum based off fork chains officially or unofficially announced supporting ProgPoW.
ProgPoW를 지지하겠다고 공식 혹은 비공식적으로 안내한 이더리움 소스 기반 포크 체인은 다음과 같습니다.
- FIXME

some other ethereum based off fork chains that try to support or prepare ProgPoW (alphabetic order)
그밖에 ProgPoW를 대비하고 있는 것으로 보이는 체인
- Ellaism (ELLA)
- EtherGEM (EGEM)
- Ethersocial Network (ESN)
- Expanse
- ~~Pirl~~

Some high network-hashrated ethereum fork chains do not try to incorporate ProgPoW. they almost do not talk or discuss ProgPoW. for example
일부 해시가 높은 체인들은 이미 ASIC에 의해서 많은 해시 비율이 점유된 것으로 보이고, 그러한 해시가 높은 체인들은 ProgPoW에 대한 논의가 거의 없는 것으로 보입니다. 그 예로
- Callisto
- Moac
- FIXME

이더리움 2.0이 PoS로 넘어가게 되면 수많은 마이너는 다른 방법의 살 길을 모색하려 할 것이며, ProgPoW가 그 하나의 실마리가 될 수 있습니다.
After Ethereum 2.0 PoS adoption. numerous miners will try to find a way to survive and the ProgPoW could be regarded as a missing key.

For this reason, Ethersocial Network also needs to try to support / discuss / study / develop ProgPoW and try to contribute ProgPoW and ethereum echo system in an open-source way.

이에 Ethersocial Network도 이를 대비하기 위한 준비/개발/토론을 해야 할 것으로 생각되며,
ProgPoW 개발을 통해서 이더리움 생태계를 오픈소스 방법을 통해 기여할 수 있을 것으로 생각합니다.

## Bounty suggestion
- ProgPoW study와 개발을 위한 월간 바운트 5,000 ESN (ProgPoW 적용 이전부터 시작 ~ 적용시점 이후 종료 (현재 적용 계획 미정))
- ProgPoW study and development. monthly bounty 5,000 ESN. (before ProgPoW adoption ~ after ProgPoW adoption applied on ESN (currently no schedule))
- ProgPoW에서 잘 작동하는 ethminer 기반 소스코드 개선 월간 5,000 ESN (ProgPoW 적용 (현재 공개된 ethminer는 알고리즘 개발을 위해서 특화되어있는 상태. CPU miner는 내장되어있지 않음, CUDA 버그도 존재함)
- fix or enhance ProgPoW-ethminer based off fork. monthly bounty 5,000 ESN (already done by ifdefelse but not ready to use. no CPU miner implemented. some CUDA / OpenCL bug exist)
- 기타 ProgPoW 대비를 위한 제반 테스트 수행을 위한 테스트넷 구성 관리
- testnet needed, fix for pool software needed, etc.
- 총 10,000 ESN 바운티. 혹은 이 에 준하는 깃허브상에서 개발 활동
- total 10,000 ESN bounty. or 10, 000 ESN equivalent all ProgPoW developments activity on github

총 바운티 월간 10, 000 ESN, total monthly bounty 10,000 ESN.

## Done
 - [x] ethereum/ethash - ProgPoW spec v0.9.1 in c language.
    - [x] open-ethereum-pool + ethereum/ethash test: successfully tested.
 - [x] ProgPoW-ethminer - rebase on top of recent ethminer master branch (v0.17.0-alpha tag)
    - [x] + ProgPoW CPU verifier using chfast/ethash. verified!
 - [x] ProgPoW-ethminer, Win 10 + Visual Studio 2017 + CUDA-9.0, CUDA-9.2, CUDA-10 build verified
## Todo
 - [ ] ProgPoW-ethminer fork - OpenCL support fix
 - [ ] some ProgPoW-ethminer optimization in ptx-level inline asm

**Comment by naikmyeong** [comment]
이 바운티는 제가 지원해 드리겠습니다.

단 아래와 같은 조건을 갗추셔야 합니다

## ProgPOW TO-DO List

+ **ProgPOW 스펙 상 버그 수정** - ProgPOW 스펙에 알려진 버그가 있을 경우 수정

+ **https://github.com/ethereum-mining/ethminer v0.16.1 & master 브랜치 기준으로 ProgPOW 지원 추가** ( 단, Appveyor 및 Travis 를 통한 빌드 검증이 되야 됨 - 윈도우 , 맥 OS, 리눅스 빌드가 되야 함 )

+ **Ethminer 개선** - 쉐어 발견 및 입력 & Progpow 와 Hashimoto 동시 지원 - ( `-progpow` 옵션을 주면 기존 ethash 에서 progpow 로 변환하게끔 개선)

+ **ethash C 라이브러리에 ProgPOW 추가** - 이건 sammy007 풀에 ProgPOW 적용을 위한 것임 https://github.com/ethereum/ethash ( https://github.com/tao-foundation/tethashv1/commit/bacea31bf83b3ae961c66b45db2670aef93c26ec  참고 )

+ **Sammy007 풀에 ProgPOW 지원 추가** - https://ethereum-magicians.org/t/what-has-to-be-done-to-get-progpow-on-ethereum/1361 에 언급 되어 있는대로 ProgPOW 의 완벽한 적용을 위해서는 노드 + 마이너 + 풀 에 progpow 적용이 되야 함/

참고로 위 조건들은 제가 TEthashV1 개발에서 구현한 목록들 중 하나임 https://github.com/tao-foundation 에 TEthashV1 을 노드 + 마이너 + 풀 에 구현한 예제가 있으니 참고해도 좋음.

총 바운티 월간 10000 ~ 15000 ESN 혹은 그에 준하는 보상 지급

**Comment by ghost** [comment]
@hackmod 
https://www.ddengle.com/esn/10255612
https://www.ddengle.com/esn/10330244

위와 같이 땡글뿐 아니라 [Github](https://github.com/EthersocialNetwork)에 개발 관련 사항들이 정리되어 다른 오픈소스 개발자들이 참조 또는 참여할 수 있도록 작업을 진행해주시길 요청합니다.

**Comment by hackmod** [comment]
thank you!
main PR post updated. all my recent work will be listed soon!

**Comment by hackmod** [comment]
PR post updated.
 - [x] ethereum/ethash - ProgPoW spec v0.9.1 in c language.
    - [x] open-ethereum-pool + ethereum/ethash test: successfully tested.
 - [x] ProgPoW-ethminer - rebase on top of recent ethminer master branch (v0.17.0-alpha tag)
    - [x] + ProgPoW CPU verifier using chfast/ethash. ***verified!***
 - [x] ProgPoW-ethminer, Win 10 + Visual Studio 2017 + CUDA-9.0, CUDA-9.2, CUDA-10 build verified

**Comment by ghost** [comment]
@hackmod 
1. 2018-11월을 관련 개발의 시작으로 하여 바운티가 지급되도록 하겠습니다.
2. 2018-12-10부터 바운티(10,000ESN) 지급을 시작합니다.
3. hackmod 외의 [Github](https://github.com/EthersocialNetwork)상에서 개발 활동에 적극적인 참여자가 발생하면 상응하는 개별 바운티도 고려하겠습니다.

**Comment by ethersocial-net** [comment]
> @hackmod
> 
> 1. 2018-11월을 관련 개발의 시작으로 하여 바운티가 지급되도록 하겠습니다.
> 2. 2018-12-10부터 바운티(10,000ESN) 지급을 시작합니다.
> 3. hackmod 외의 [Github](https://github.com/EthersocialNetwork)상에서 개발 활동에 적극적인 참여자가 발생하면 상응하는 개별 바운티도 고려하겠습니다.

This issue has been accepted. The reward will be paid from Dec 2018 (10,000 ESN per month)
We are also considering individual bounty for anyone who actively contributes development in Github.

**Comment by hackmod** [comment]
* [x] ***outdated*** https://github.com/ifdefelse/ProgPOW/issues/17 
* [x] https://github.com/ethereum-mining/ethminer/pull/1766 (spec v0.9.2) 12/09

**Comment by riddlez666** [comment]
EGEM is actively following and working towards ProgPOW.

**Comment by hackmod** [comment]
ProgPoW-ethminer snapshot is available at https://github.com/hackmod/ethminer/releases/tag/v0.9.2-progpow-1214
